
services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Bethuelresumedb
      POSTGRES_USER: Bethuel
      POSTGRES_PASSWORD: 23498812
    volumes:
      - pg_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: bethuelmoukangwe@gmail.com  # Set your admin email
      PGADMIN_DEFAULT_PASSWORD: 23498812  # Set a strong password here
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data:
