version: '3.8'

services:
  web:
    build: .
    command: gunicorn portfolio.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Bethuelresumedb
      POSTGRES_USER: Bethuel
      POSTGRES_PASSWORD: 23498812
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

