version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount the entire project directory for development
    environment:
      - DEBUG=1
      - DATABASE_URL=postgres://Bethuel:23498812@db:5432/Bethuelresumedb
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=Bethuelresumedb
      - POSTGRES_USER=Bethuel
      - POSTGRES_PASSWORD=23498812
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
