name: Build and Publish image to Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: Bethuelresumedb
          POSTGRES_USER: Bethuel
          POSTGRES_PASSWORD: 23498812
        ports:
          - 5432:5432
        volumes:
          - pg_data:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Ensure correct reference to Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}    # Ensure correct reference to Docker password

      - name: Build Docker image
        run: docker build . -t bethuelm/portfolio-app:latest

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec web python manage.py test  # Fixed typo from 'testry' to 'test'
          docker-compose down

      - name: Push Docker image to Docker Hub
        run: docker push bethuelm/portfolio-app:latest  # Fixed typo: added space before the image name

volumes:
  pg_data:
