name: Build and Publish image to Docker Hub

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: Bethuelresumedb
          POSTGRES_USER: Bethuel
          POSTGRES_PASSWORD: 23498812
        ports:
          - 5432:5432
        volumes:
          - pg_data:/var/lib/postgresql/data

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Verify Docker login
        run: docker info

      - name: Build Docker image
        run: docker build --progress=plain . -t bethuelm/portfolio-app:latest

      - name: List Docker images
        run: docker images  # List images for debugging

      - name: Run tests
        run: |
          docker-compose up -d
          docker-compose exec web python manage.py test
          docker-compose down

      - name: Push Docker image to Docker Hub
        run: docker push bethuelm/portfolio-app:latest


